name: at_app_create
description: A library to build your own custom implementation of flutter create.
version: 0.2.0
repository: https://github.com/atsign-foundation/at_app/tree/trunk/packages/at_app_create/
homepage: https://atsign.dev/

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  json_annotation: ^4.4.0
  mason: ^0.1.0-dev.8
  pub_semver: ^2.1.0
  universal_io: ^2.0.4
  args: ^2.3.0
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  lints: ">=1.0.0 <3.0.0"
  test: ^1.16.0
