name: {{projectName}}
description: {{description}}
version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
{{#dependencies}}  {{.}}
{{/dependencies}}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
{{#flutterConfig}}  {{.}}
{{/flutterConfig}}
