name: app_template
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_client_mobile: ^3.0.3
  at_utils: ^3.0.0
  path_provider: ^2.0.5
  flutter_dotenv: ^5.0.2
  at_app_flutter: ^5.0.0

env:
  include: true
  gitignore: true

android:
  enableR8: true
  kotlinVersion: 1.5.32
  minSdkVersion: '23'
