name: at_app_flutter
description: A library that help developers build flutter applications on the @platform.
version: 5.0.0+2
repository: https://github.com/atsign-foundation/at_app/tree/trunk/packages/at_app_flutter/
homepage: https://atsign.dev/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  at_onboarding_flutter: ^4.0.0
  at_utils: ^3.0.5
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.0
  mockito: ^5.1.0
  meta: ^1.7.0
