name: at_app_bundler
description: A command-line bundler for at_app_create templates.
version: 0.2.0
repository: https://github.com/atsign-foundation/at_app/tree/trunk/packages/at_app_bundler/
homepage: https://atsign.dev/

executables:
  at_app_bundler: at_app_bundler

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  args: ^2.3.0
  mason: 0.1.0-dev.8
  mason_cli: 0.1.0-dev.12
  mason_logger: ^0.1.0-dev.5
  pub_semver: ^2.1.0
  yaml: ^3.1.0
  path: ^1.8.1

dev_dependencies:
  lints: ">=1.0.0 <3.0.0"
