name: at_follows_flutter_template
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path_provider: ^2.0.11
  flutter_local_notifications: ^9.1.4
  at_app_flutter: ^5.0.0
  at_onboarding_flutter: ^4.0.0
  at_follows_flutter: ^3.0.7
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

env:
  override: true

env_override:
  NAMESPACE: productive2227
  API_KEY: 477b-876u-bcez-c42z-6a3d

android:
  enableR8: true
  kotlinVersion: 1.5.32
  minSdkVersion: '24'
