name: at_theme_flutter_template
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_common_flutter: ^2.0.8
  cupertino_icons: ^1.0.5
  at_theme_flutter: ^1.0.2
  at_app_flutter: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - .env
  uses-material-design: true

env:
  override: true

env_override:
  NAMESPACE: productive2227
  API_KEY: 477b-876u-bcez-c42z-6a3d

android:
  enableR8: true
  kotlinVersion: 1.5.32
  minSdkVersion: '24'

