name: at_invitation_flutter_template
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_app_flutter: ^5.0.0
  at_invitation_flutter: ^2.0.0
  cupertino_icons: ^1.0.5
  uni_links: ^0.5.1
  url_launcher: ^6.1.4

env:
  override: true

env_override:
  NAMESPACE: productive2227
  API_KEY: 477b-876u-bcez-c42z-6a3d

android:
  enableR8: true
  kotlinVersion: 1.5.32
  minSdkVersion: '24'
