name: at_location_flutter_template
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  at_app_flutter: ^5.0.0+1
  at_location_flutter: ^3.1.5
  latlong2: ^0.8.1
  at_onboarding_flutter: ^4.0.3

env:
  override: true

env_override:
  NAMESPACE: productive2227
  API_KEY: 477b-876u-bcez-c42z-6a3d

android:
  enableR8: true
  kotlinVersion: 1.5.32
  minSdkVersion: '24'
