name: at_contacts_group_flutter_template
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_contacts_group_flutter: ^4.0.9
  cupertino_icons: ^1.0.5
  at_contacts_flutter: ^4.0.7
  at_app_flutter: ^5.0.1
  at_onboarding_flutter: ^6.0.2
  biometric_storage: ^4.1.3

env:
  override: true

env_override:
  NAMESPACE: productive2227
  API_KEY: 477b-876u-bcez-c42z-6a3d

